### ISSUE TITLE
Tags cannot be created directly in records

### ISSUE THREAD

**Issue by presedo** [IchHabRecht/t3tags#2]
Hi, 
Just installed t3tags on a new TYPO3 9.5.7 instance, and configured the TCA override like this
```
/** @var TagRegistry $tagRegistry */
$tagRegistry = GeneralUtility::makeInstance(TagRegistry::class);

$tagRegistry->makeTaggable(
    $tableName,
    'tags',
    [
        'label' => 'Tags',
        'position' => 'after:description',
        'fieldConfiguration' => [
        ],
    ],
    true
);
```
Really minimal configuration.

In the README.md file, I read "New tags can be added on the fly and are created only when the record is saved", but I don't see where to create them... In the backend, I see the the field, but I cannot create new tags directly in the record form. 
 [Here is what I see](https://pasteboard.co/Igpa35f.png)
I must create the tags first and then select them in the record ?

**Comment by IchHabRecht** [comment]
Hi @presedo,

If you enter any (new) tag in the "find records" search field, you should see an option to add a new tag.

Please remember that your extension that makes usage of TagRegistry needs to provide the database field (tags) on its own.

**Comment by IchHabRecht** [comment]
As there wasn't any feedback here, I'm closing the issue now.
