### ISSUE TITLE
 Reference Index: Unknown column 'my_pagetags' in 'field list'

### ISSUE THREAD

**Issue by joeschi** [IchHabRecht/t3tags#3]
I created a new field "my_tags" in the table pages, registered the new field in Overrides/Pages.php  as described.
But running the Typo3 Reference Index-Update i got SQL-Errors (Typo3 8.7.31):

In AbstractMySQLDriver.php line 71:
Unknown column 'my_pagetags' in 'field list'

In MysqliStatement.php line 94:
Unknown column 'my_pagetags' in 'field list'

Everything works, the field exists in the database, only updating the ReferenceIndex fails.

**Comment by IchHabRecht** [comment]
Hi @joeschi,

As the extension only provides functions to help with TCA and PHP api, you need to add your new field to the ext_tables.sql of your own extension. Afterwards you need to make sure the field is created by either turn your extension off/on or check the database with the database wizard.

**Comment by joeschi** [comment]
Thanks for your reply. I already added the new field. And as i described in the backend everything works fine.
- Updating the ReferenceIndex fails with given errors
- Additionaly Typo3 creates randomly(?) references from other extensions to new created t3tags.
Hmmm.

**Comment by joeschi** [comment]
Meanwhile i figuered out, that an entry in /t3tags/Configuration/TCA/tx_t3tags_tag.php caused the wrong references. The "items"-column-config-mm must be 'tx_t3tags_tag_mm' instead of 'sys_category_record_mm'.
The problem with reference-index still exists. I suppose it is an issue with the tca-configuration.

**Comment by joeschi** [comment]
Aaargh, finally i found the reason for the error trying to update the referenceindex. I was in development-context, but the cli-script didn't respect my database-entries for development-context in AdditionalConfiguation.php. 

Indepentently from that i suggest to change the tca-configuration for the field "items" in /t3tags/Configuration/TCA/tx_t3tags_tag.php.
The "items"-column-config-mm must be 'tx_t3tags_tag_mm' instead of 'sys_category_record_mm'.

**Comment by IchHabRecht** [comment]
Hi @joeschi,

Thank you for your feedback. The TCA has been fixed in 1.0.1.
